import { Cart, Order } from "klikni-jadi-shared-stuff";
import { Timestamp } from "firebase-admin/firestore";

export const getCart = (
  type: "no-minimum-order" | "kjd-cart" | "kjd-cart-preorder" | "success"
) => {
  switch (type) {
    case "no-minimum-order":
      return {
        roundup: 0,
        host: {
          id: "lHYojBWozigmML8q1gM9iSeuI6G2",
          cartId: "",
          phone: {
            countryCode: "389",
            fullNumber: "38972233943",
            phoneNumber: "72233943",
          },
          address: {
            accommodation: "apartment",
            location: { longitude: 21.3850289, latitude: 42.0005009 },
            doorPin: "/",
            id: "1wOxZtxs4cP2S85sqAW6",
            approved: false,
            apartmentNumber: "/",
            isDefault: true,
            entranceNumber: "/",
            streetNumber: "/",
            fullAddress: "Budimpestanska 28, Skopje, North Macedonia",
            city: "Skopje",
          },
          firstName: "Naum",
          email: "",
          lastName: "Shapkarovski",
        },
        takeoutDiscount: 0,
        restaurantIds: ["1uIqpWS64BLHR1nzqRtN"],
        itemsTotalPrice: 150,
        groupedItems: {
          "1uIqpWS64BLHR1nzqRtN": {
            foodMenuId: null,
            restaurantName: { en: "Gluvo Kuce", mk: "Глуво Куче" },
            items: {
              ZqWxWM14azeM714g8E43: {
                selectedPortionId: null,
                itemNo: "55330",
                ingredients: null,
                quantity: 1,
                excluded: [],
                name: {
                  mk: "Домашен Пекарски Компир",
                  en: "Homemade Baked Potatoes",
                },
                finalPrice: 150,
                comment: "",
                id: "6o3YOWwOULxPxY79lo6S",
                portions: null,
                imageUrl: "",
              },
            },
            restaurantLogoUrl:
              "http://lh3.googleusercontent.com/GH_vgop5JU2y1jQTb5Tuwxw-YQ_rqZNgsMMqBv-2CjruJCYqNcEbdiw3mQFIaM_26TqtjqEIhyLvh62kldGAVnH2INOhRaARr3N-yceojbz0du0",
            restaurantPhones: [{ name: "", phoneNumber: "0038971721545" }],
            restaurantRoundup: 0,
            restaurantId: "1uIqpWS64BLHR1nzqRtN",
            restaurantTotalItemsPrice: 150,
            restaurantAddress: {
              location: {
                longitude: 21.4259201071015,
                latitude: 42.001630913556,
              },
              fullAddress: "ул. Ристо Шишков бр.25",
              city: "Skopje",
            },
          },
        },
        type: "delivery",
        deliveryFee: 74,
      } as Cart;

    case "success":
      return {
        roundup: 0,
        host: {
          id: "lHYojBWozigmML8q1gM9iSeuI6G2",
          cartId: "",
          phone: {
            countryCode: "389",
            fullNumber: "38972233943",
            phoneNumber: "72233943",
          },
          address: {
            accommodation: "apartment",
            location: { longitude: 21.3850289, latitude: 42.0005009 },
            doorPin: "/",
            id: "1wOxZtxs4cP2S85sqAW6",
            approved: false,
            apartmentNumber: "/",
            isDefault: true,
            entranceNumber: "/",
            streetNumber: "/",
            fullAddress: "Budimpestanska 28, Skopje, North Macedonia",
            city: "Skopje",
          },
          firstName: "Naum",
          email: "",
          lastName: "Shapkarovski",
        },
        takeoutDiscount: 0,
        restaurantIds: ["1uIqpWS64BLHR1nzqRtN"],
        itemsTotalPrice: 450,
        groupedItems: {
          "1uIqpWS64BLHR1nzqRtN": {
            foodMenuId: null,
            restaurantName: { en: "Gluvo Kuce", mk: "Глуво Куче" },
            items: {
              ZqWxWM14azeM714g8E43: {
                selectedPortionId: null,
                itemNo: "55330",
                ingredients: null,
                quantity: 3,
                excluded: [],
                name: {
                  mk: "Домашен Пекарски Компир",
                  en: "Homemade Baked Potatoes",
                },
                finalPrice: 150,
                comment: "",
                id: "6o3YOWwOULxPxY79lo6S",
                portions: null,
                imageUrl: "",
              },
            },
            restaurantLogoUrl:
              "http://lh3.googleusercontent.com/GH_vgop5JU2y1jQTb5Tuwxw-YQ_rqZNgsMMqBv-2CjruJCYqNcEbdiw3mQFIaM_26TqtjqEIhyLvh62kldGAVnH2INOhRaARr3N-yceojbz0du0",
            restaurantPhones: [{ name: "", phoneNumber: "0038971721545" }],
            restaurantRoundup: 0,
            restaurantId: "1uIqpWS64BLHR1nzqRtN",
            restaurantTotalItemsPrice: 450,
            restaurantAddress: {
              location: {
                longitude: 21.4259201071015,
                latitude: 42.001630913556,
              },
              fullAddress: "ул. Ристо Шишков бр.25",
              city: "Skopje",
            },
          },
        },
        type: "delivery",
        deliveryFee: 74,
      } as Cart;

    case "kjd-cart":
      return {
        id: "kjdCart",
        roundup: 0,
        host: {
          id: "lHYojBWozigmML8q1gM9iSeuI6G2",
          cartId: "",
          phone: {
            countryCode: "389",
            fullNumber: "38972233943",
            phoneNumber: "72233943",
          },
          address: {
            accommodation: "apartment",
            location: { longitude: 21.3850289, latitude: 42.0005009 },
            doorPin: "/",
            id: "1wOxZtxs4cP2S85sqAW6",
            approved: false,
            apartmentNumber: "/",
            isDefault: true,
            entranceNumber: "/",
            streetNumber: "/",
            fullAddress: "Budimpestanska 28, Skopje, North Macedonia",
            city: "Skopje",
          },
          firstName: "Naum",
          email: "",
          lastName: "Shapkarovski",
        },
        takeoutDiscount: 0,
        restaurantIds: ["1uIqpWS64BLHR1nzqRtN"],
        itemsTotalPrice: 450,
        groupedItems: {
          "1uIqpWS64BLHR1nzqRtN": {
            foodMenuId: null,
            restaurantName: { en: "Gluvo Kuce", mk: "Глуво Куче" },
            items: {
              ZqWxWM14azeM714g8E43: {
                selectedPortionId: null,
                itemNo: "55330",
                ingredients: null,
                quantity: 3,
                excluded: [],
                name: {
                  mk: "Домашен Пекарски Компир",
                  en: "Homemade Baked Potatoes",
                },
                finalPrice: 150,
                comment: "",
                id: "6o3YOWwOULxPxY79lo6S",
                portions: null,
                imageUrl: "",
              },
            },
            restaurantLogoUrl:
              "http://lh3.googleusercontent.com/GH_vgop5JU2y1jQTb5Tuwxw-YQ_rqZNgsMMqBv-2CjruJCYqNcEbdiw3mQFIaM_26TqtjqEIhyLvh62kldGAVnH2INOhRaARr3N-yceojbz0du0",
            restaurantPhones: [{ name: "", phoneNumber: "0038971721545" }],
            restaurantRoundup: 0,
            restaurantId: "1uIqpWS64BLHR1nzqRtN",
            restaurantTotalItemsPrice: 450,
            restaurantAddress: {
              location: {
                longitude: 21.4259201071015,
                latitude: 42.001630913556,
              },
              fullAddress: "ул. Ристо Шишков бр.25",
              city: "Skopje",
            },
          },
        },
        type: "delivery",
        deliveryFee: 74,
      } as Cart;

    case "kjd-cart-preorder":
      const deliveryDate = new Date();
      return {
        id: "kjdCart",
        roundup: 0,
        deliveryDate: Timestamp.fromMillis(
          deliveryDate.setHours(deliveryDate.getHours() + 2)
        ),
        host: {
          id: "lHYojBWozigmML8q1gM9iSeuI6G2",
          cartId: "",
          phone: {
            countryCode: "389",
            fullNumber: "38972233943",
            phoneNumber: "72233943",
          },
          address: {
            accommodation: "apartment",
            location: { longitude: 21.3850289, latitude: 42.0005009 },
            doorPin: "/",
            id: "1wOxZtxs4cP2S85sqAW6",
            approved: false,
            apartmentNumber: "/",
            isDefault: true,
            entranceNumber: "/",
            streetNumber: "/",
            fullAddress: "Budimpestanska 28, Skopje, North Macedonia",
            city: "Skopje",
          },
          firstName: "Naum",
          email: "",
          lastName: "Shapkarovski",
        },
        takeoutDiscount: 0,
        restaurantIds: ["1uIqpWS64BLHR1nzqRtN"],
        itemsTotalPrice: 450,
        groupedItems: {
          "1uIqpWS64BLHR1nzqRtN": {
            foodMenuId: null,
            restaurantName: { en: "Gluvo Kuce", mk: "Глуво Куче" },
            items: {
              ZqWxWM14azeM714g8E43: {
                selectedPortionId: null,
                itemNo: "55330",
                ingredients: null,
                quantity: 3,
                excluded: [],
                name: {
                  mk: "Домашен Пекарски Компир",
                  en: "Homemade Baked Potatoes",
                },
                finalPrice: 150,
                comment: "",
                id: "6o3YOWwOULxPxY79lo6S",
                portions: null,
                imageUrl: "",
              },
            },
            restaurantLogoUrl:
              "http://lh3.googleusercontent.com/GH_vgop5JU2y1jQTb5Tuwxw-YQ_rqZNgsMMqBv-2CjruJCYqNcEbdiw3mQFIaM_26TqtjqEIhyLvh62kldGAVnH2INOhRaARr3N-yceojbz0du0",
            restaurantPhones: [{ name: "", phoneNumber: "0038971721545" }],
            restaurantRoundup: 0,
            restaurantId: "1uIqpWS64BLHR1nzqRtN",
            restaurantTotalItemsPrice: 450,
            restaurantAddress: {
              location: {
                longitude: 21.4259201071015,
                latitude: 42.001630913556,
              },
              fullAddress: "ул. Ристо Шишков бр.25",
              city: "Skopje",
            },
          },
        },
        isPreorder: true,
        type: "delivery",
        deliveryFee: 74,
      } as Cart;
  }
};

export const getOrder = (type: "before" | "after" | "delivered" | "placed") => {
  switch (type) {
    case "placed":
      return {
        deliveryFee: 74,
        payment: "cash",
        total: 524,
        type: "delivery",
        restaurant: {
          images: {
            logoUrl:
              "http://lh3.googleusercontent.com/GH_vgop5JU2y1jQTb5Tuwxw-YQ_rqZNgsMMqBv-2CjruJCYqNcEbdiw3mQFIaM_26TqtjqEIhyLvh62kldGAVnH2INOhRaARr3N-yceojbz0du0",
          },
          deliveryPricePerKm: 10,
          id: "1uIqpWS64BLHR1nzqRtN",
          address: {
            location: {
              longitude: 21.4259201071015,
              latitude: 42.001630913556,
            },
            fullAddress: "ул. Ристо Шишков бр.25",
            city: "Skopje",
          },
          phones: [{ name: "", phoneNumber: "0038971721545" }],
          name: { mk: "Глуво Куче", en: "Gluvo Kuce" },
          minOrderAmount: 0,
        },
        pickupTime: new Timestamp(1639076271, 614000000),
        platform: "web",
        coupon: "",
        deliveryTime: {
          maximumDeliveryTime: new Timestamp(1639075071, 614000000),
          minimumDeliveryTime: new Timestamp(1639077291, 614000000),
        },
        wallet: 0,
        service: "kjd",
        deliveryDate: new Timestamp(639075071, 614000000),
        customer: {
          email: "",
          cartId: "",
          id: "lHYojBWozigmML8q1gM9iSeuI6G2",
          address: {
            fullAddress: "Budimpestanska 28, Skopje, North Macedonia",
            city: "Skopje",
            isDefault: true,
            id: "1wOxZtxs4cP2S85sqAW6",
            doorPin: "/",
            approved: false,
            location: { longitude: 21.3850289, latitude: 42.0005009 },
            entranceNumber: "/",
            streetNumber: "/",
            apartmentNumber: "/",
            accommodation: "apartment",
          },
          firstName: "Naum",
          phone: {
            phoneNumber: "72233943",
            countryCode: "389",
            fullNumber: "38972233943",
          },
          lastName: "Shapkarovski",
        },
        tip: 0,
        items: {
          ZqWxWM14azeM714g8E43: {
            markup: { inhouse: 10, internal: 10, delivery: 10, takeout: 10 },
            excluded: [],
            portions: null,
            comment: "",
            discountedPrice: null,
            ingredients: null,
            basePrice: 130,
            round: { takeout: 10, internal: 10, inhouse: 10, delivery: 10 },
            imageUrl: "",
            selectedPortionId: null,
            id: "6o3YOWwOULxPxY79lo6S",
            finalPrice: 150,
            name: {
              en: "Homemade Baked Potatoes",
              mk: "Домашен Пекарски Компир",
            },
            itemNo: "55330",
            quantity: 3,
            rabat: { inhouse: 10, takeout: 10, internal: 10, delivery: 10 },
          },
        },
        status: "placed",
        statusChangeLog: {
          placedAt: new Timestamp(1639075071, 614000000),
        },
        itemsTotalPrice: 450,
        isPriority: false,
        orderNo: 1752,
        createdAt: new Timestamp(1639075071, 614000000),
        roundup: 0,
        refund: "no",
        driverComment: "",
        priorityFee: 0,
      } as Order;

    case "before":
      return {
        deliveryFee: 74,
        payment: "cash",
        total: 524,
        type: "delivery",
        restaurant: {
          images: {
            logoUrl:
              "http://lh3.googleusercontent.com/GH_vgop5JU2y1jQTb5Tuwxw-YQ_rqZNgsMMqBv-2CjruJCYqNcEbdiw3mQFIaM_26TqtjqEIhyLvh62kldGAVnH2INOhRaARr3N-yceojbz0du0",
          },
          deliveryPricePerKm: 10,
          id: "1uIqpWS64BLHR1nzqRtN",
          address: {
            location: {
              longitude: 21.4259201071015,
              latitude: 42.001630913556,
            },
            fullAddress: "ул. Ристо Шишков бр.25",
            city: "Skopje",
          },
          phones: [{ name: "", phoneNumber: "0038971721545" }],
          name: { mk: "Глуво Куче", en: "Gluvo Kuce" },
          minOrderAmount: 0,
        },
        pickupTime: new Timestamp(1639076271, 614000000),
        platform: "web",
        coupon: "",
        deliveryTime: {
          maximumDeliveryTime: new Timestamp(1639075071, 614000000),
          minimumDeliveryTime: new Timestamp(1639077291, 614000000),
        },
        wallet: 0,
        service: "kjd",
        deliveryDate: new Timestamp(639075071, 614000000),
        customer: {
          email: "",
          cartId: "",
          id: "lHYojBWozigmML8q1gM9iSeuI6G2",
          address: {
            fullAddress: "Budimpestanska 28, Skopje, North Macedonia",
            city: "Skopje",
            isDefault: true,
            id: "1wOxZtxs4cP2S85sqAW6",
            doorPin: "/",
            approved: false,
            location: { longitude: 21.3850289, latitude: 42.0005009 },
            entranceNumber: "/",
            streetNumber: "/",
            apartmentNumber: "/",
            accommodation: "apartment",
          },
          firstName: "Naum",
          phone: {
            phoneNumber: "72233943",
            countryCode: "389",
            fullNumber: "38972233943",
          },
          lastName: "Shapkarovski",
        },
        tip: 0,
        items: {
          ZqWxWM14azeM714g8E43: {
            markup: { inhouse: 10, internal: 10, delivery: 10, takeout: 10 },
            excluded: [],
            portions: null,
            comment: "",
            discountedPrice: null,
            ingredients: null,
            basePrice: 130,
            round: { takeout: 10, internal: 10, inhouse: 10, delivery: 10 },
            imageUrl: "",
            selectedPortionId: null,
            id: "6o3YOWwOULxPxY79lo6S",
            finalPrice: 150,
            name: {
              en: "Homemade Baked Potatoes",
              mk: "Домашен Пекарски Компир",
            },
            itemNo: "55330",
            quantity: 3,
            rabat: { inhouse: 10, takeout: 10, internal: 10, delivery: 10 },
          },
        },
        status: "pending",
        statusChangeLog: {
          placedAt: new Timestamp(1639075071, 614000000),
        },
        itemsTotalPrice: 450,
        isPriority: false,
        orderNo: 1752,
        createdAt: new Timestamp(1639075071, 614000000),
        roundup: 0,
        refund: "no",
        driverComment: "",
        priorityFee: 0,
      } as Order;

    case "after":
      return {
        deliveryFee: 74,
        payment: "cash",
        total: 524,
        type: "delivery",
        restaurant: {
          images: {
            logoUrl:
              "http://lh3.googleusercontent.com/GH_vgop5JU2y1jQTb5Tuwxw-YQ_rqZNgsMMqBv-2CjruJCYqNcEbdiw3mQFIaM_26TqtjqEIhyLvh62kldGAVnH2INOhRaARr3N-yceojbz0du0",
          },
          deliveryPricePerKm: 10,
          id: "1uIqpWS64BLHR1nzqRtN",
          address: {
            location: {
              longitude: 21.4259201071015,
              latitude: 42.001630913556,
            },
            fullAddress: "ул. Ристо Шишков бр.25",
            city: "Skopje",
          },
          phones: [{ name: "", phoneNumber: "0038971721545" }],
          name: { mk: "Глуво Куче", en: "Gluvo Kuce" },
          minOrderAmount: 0,
        },
        pickupTime: new Timestamp(1639077271, 614000000),
        platform: "web",
        coupon: "",
        deliveryTime: {
          maximumDeliveryTime: new Timestamp(1639075071, 614000000),
          minimumDeliveryTime: new Timestamp(1639077291, 614000000),
        },
        wallet: 0,
        service: "kjd",
        deliveryDate: new Timestamp(639075071, 614000000),
        customer: {
          email: "",
          cartId: "",
          id: "lHYojBWozigmML8q1gM9iSeuI6G2",
          address: {
            fullAddress: "Budimpestanska 28, Skopje, North Macedonia",
            city: "Skopje",
            isDefault: true,
            id: "1wOxZtxs4cP2S85sqAW6",
            doorPin: "/",
            approved: false,
            location: { longitude: 21.3850289, latitude: 42.0005009 },
            entranceNumber: "/",
            streetNumber: "/",
            apartmentNumber: "/",
            accommodation: "apartment",
          },
          firstName: "Naum",
          phone: {
            phoneNumber: "72233943",
            countryCode: "389",
            fullNumber: "38972233943",
          },
          lastName: "Shapkarovski",
        },
        tip: 0,
        items: {
          ZqWxWM14azeM714g8E43: {
            markup: { inhouse: 10, internal: 10, delivery: 10, takeout: 10 },
            excluded: [],
            portions: null,
            comment: "",
            discountedPrice: null,
            ingredients: null,
            basePrice: 130,
            round: { takeout: 10, internal: 10, inhouse: 10, delivery: 10 },
            imageUrl: "",
            selectedPortionId: null,
            id: "6o3YOWwOULxPxY79lo6S",
            finalPrice: 150,
            name: {
              en: "Homemade Baked Potatoes",
              mk: "Домашен Пекарски Компир",
            },
            itemNo: "55330",
            quantity: 3,
            rabat: { inhouse: 10, takeout: 10, internal: 10, delivery: 10 },
          },
        },
        status: "pending",
        statusChangeLog: {
          placedAt: new Timestamp(1639075071, 614000000),
        },
        itemsTotalPrice: 450,
        isPriority: false,
        orderNo: 1752,
        createdAt: new Timestamp(1639075071, 614000000),
        roundup: 0,
        refund: "no",
        driverComment: "",
        priorityFee: 0,
      } as Order;

    case "delivered":
      return {
        deliveryFee: 74,
        payment: "cash",
        total: 524,
        type: "delivery",
        restaurant: {
          images: {
            logoUrl:
              "http://lh3.googleusercontent.com/GH_vgop5JU2y1jQTb5Tuwxw-YQ_rqZNgsMMqBv-2CjruJCYqNcEbdiw3mQFIaM_26TqtjqEIhyLvh62kldGAVnH2INOhRaARr3N-yceojbz0du0",
          },
          deliveryPricePerKm: 10,
          id: "1uIqpWS64BLHR1nzqRtN",
          address: {
            location: {
              longitude: 21.4259201071015,
              latitude: 42.001630913556,
            },
            fullAddress: "ул. Ристо Шишков бр.25",
            city: "Skopje",
          },
          phones: [{ name: "", phoneNumber: "0038971721545" }],
          name: { mk: "Глуво Куче", en: "Gluvo Kuce" },
          minOrderAmount: 0,
        },
        pickupTime: new Timestamp(1639077271, 614000000),
        platform: "web",
        coupon: "",
        deliveryTime: {
          maximumDeliveryTime: new Timestamp(1639075071, 614000000),
          minimumDeliveryTime: new Timestamp(1639077291, 614000000),
        },
        wallet: 0,
        service: "kjd",
        deliveryDate: Timestamp.now(),
        customer: {
          email: "",
          cartId: "",
          id: "lHYojBWozigmML8q1gM9iSeuI6G2",
          address: {
            fullAddress: "Budimpestanska 28, Skopje, North Macedonia",
            city: "Skopje",
            isDefault: true,
            id: "1wOxZtxs4cP2S85sqAW6",
            doorPin: "/",
            approved: false,
            location: { longitude: 21.3850289, latitude: 42.0005009 },
            entranceNumber: "/",
            streetNumber: "/",
            apartmentNumber: "/",
            accommodation: "apartment",
          },
          firstName: "Naum",
          phone: {
            phoneNumber: "72233943",
            countryCode: "389",
            fullNumber: "38972233943",
          },
          lastName: "Shapkarovski",
        },
        tip: 0,
        items: {
          ZqWxWM14azeM714g8E43: {
            markup: { inhouse: 10, internal: 10, delivery: 10, takeout: 10 },
            excluded: [],
            portions: null,
            comment: "",
            discountedPrice: null,
            ingredients: null,
            basePrice: 130,
            round: { takeout: 10, internal: 10, inhouse: 10, delivery: 10 },
            imageUrl: "",
            selectedPortionId: null,
            id: "6o3YOWwOULxPxY79lo6S",
            finalPrice: 150,
            name: {
              en: "Homemade Baked Potatoes",
              mk: "Домашен Пекарски Компир",
            },
            itemNo: "55330",
            quantity: 3,
            rabat: { inhouse: 10, takeout: 10, internal: 10, delivery: 10 },
          },
        },
        status: "delivered",
        statusChangeLog: {
          placedAt: new Timestamp(1639075071, 614000000),
        },
        itemsTotalPrice: 450,
        isPriority: false,
        orderNo: 1752,
        createdAt: new Timestamp(1639075071, 614000000),
        roundup: 0,
        refund: "no",
        driverComment: "",
        priorityFee: 0,
      } as Order;
  }
};

export const getRestaurant = () => {
  return {
    occupationIds: [{ priority: 1, id: "H5j7T0C7894o5URtd4We" }],
    createdAt: new Timestamp(1632319698, 118000000),
    videos: { coverRef: "", coverUrl: "" },
    images: {
      coverRef:
        "restaurants/0RwbqFHdsFBVgICik0Os/media/1497_070421133909630_1900x600",
      coverUrl:
        "http://lh3.googleusercontent.com/MlECI0qRqUAILt8KnXD25XSn-MgvdUL9U97oNWO_jKTXAntyI1LAeMgZ3eQVM_2tDlVZ4wHbEmtYPpP5RQM8yt2DDJ0No-n1Ppj2EAmKJxzAIKo",
      thumbnailRef: "",
      logoUrl:
        "http://lh3.googleusercontent.com/SUGYacXuLcyIpwNdabbWfyg5OFDqEOsDk6p8pJYRS3DgtoMYjjz3bKyfQIdVHsAgtjAFK1MJtJaH7fDbwQjlyOrFynDlfEOZKGzhh1T79ek0Y6pk",
      thumbnailUrl:
        "https://p0.pikist.com/photos/1/121/burger-food-restaurant-beautiful-healthy-food-macro-nutrition-kitchen-health-thumbnail.jpg",
      logoRef:
        "restaurants/0RwbqFHdsFBVgICik0Os/media/1497_070421132112302_400x400",
    },
    name: { mk: "Фрут Ленд", en: "Fruit Land" },
    workingHours: {
      booking: {
        tue: [{ from: "0900", to: "1500" }],
        wed: [{ to: "1500", from: "0900" }],
        thu: [{ to: "1500", from: "0900" }],
        sat: [{ from: "1000", to: "1500" }],
        mon: [{ to: "1500", from: "0900" }],
        fri: [{ to: "1500", from: "0900" }],
        sun: [{ from: "1000", to: "1000" }],
      },
      delivery: {
        fri: [{ from: "0900", to: "1500" }],
        thu: [{ to: "1500", from: "0900" }],
        sun: [{ from: "1000", to: "1000" }],
        tue: [{ from: "0900", to: "1500" }],
        mon: [{ from: "0900", to: "1500" }],
        sat: [{ to: "1500", from: "1000" }],
        wed: [{ from: "0900", to: "1500" }],
      },
    },
    sections: { isSponsored: false },
    address: {
      location: { latitude: 41.9848986352984, longitude: 21.4611907725681 },
      fullAddress: "Бул.Јане Сандански бр.40",
      city: "Skopje",
    },
    hideFromSearch: false,
    amenityIds: [],
    attributes: {
      hasEmailForRating: true,
      hasTableBooking: false,
      hasSelfPickup: true,
      hasInhouse: true,
      deliveryBy: "kjd",
      hasDelivery: false,
    },
    avgRating: 0,
    activeFoodMenuId: "ZI5FWM1QrRGgjbF4ieV5",
    phones: [{ phoneNumber: "0038978332193", name: "" }],
    description: { en: "", mk: "" },
    timesOff: [],
    priorityNumber: 0,
    subtitle: { en: "", mk: "" },
    id: "0RwbqFHdsFBVgICik0Os",
    status: {
      isActive: true,
      isOpenForBooking: false,
      isOpenForDelivery: true,
      isNew: true,
    },
    gallery: [],
    searchableIndex: {
      "fruit lan": true,
      fr: true,
      "Fruit Lan": true,
      "Фрут Лен": true,
      фру: true,
      "Fruit Land": true,
      "Фрут Л": true,
      Ф: true,
      Фр: true,
      "fruit la": true,
      фр: true,
      "Fruit La": true,
      Fru: true,
      ф: true,
      "Fruit L": true,
      f: true,
      Фру: true,
      "fruit ": true,
      F: true,
      "фрут ленд": true,
      "фрут ле": true,
      "Fruit ": true,
      "Фрут ": true,
      "Фрут Ле": true,
      "фрут ": true,
      "фрут лен": true,
      fruit: true,
      "Фрут Ленд": true,
      "фрут л": true,
      фрут: true,
      Frui: true,
      fru: true,
      "fruit l": true,
      "fruit land": true,
      frui: true,
      Fruit: true,
      Fr: true,
      Фрут: true,
    },
    cuisineIds: [{ id: "1CLi8NrxDRV749AO6a6p", priority: 1 }],
  };
};

export const getSettings = () => {
  return {
    company: {
      name: "Klikni Jadi",
      stampSignImageUrl: "",
      account: "",
      stampSignImageRef: "",
      bank: "",
    },
    coupons: {
      codes: [
        {
          uses: 12,
          from: { _seconds: 1627484526, _nanoseconds: 322000000 },
          to: { _seconds: 1627657320, _nanoseconds: 0 },
          code: "NAUM",
        },
        {
          to: { _seconds: 1633787220, _nanoseconds: 0 },
          uses: 1,
          code: "AAA",
          from: { _seconds: 1633700869, _nanoseconds: 698000000 },
        },
        {
          uses: 5,
          code: "Elena",
          from: { _seconds: 1633346590, _nanoseconds: 0 },
          to: { _seconds: 1634988190, _nanoseconds: 0 },
        },
        {
          to: { _seconds: 1634901960, _nanoseconds: 0 },
          from: { _seconds: 1634210774, _nanoseconds: 369000000 },
          uses: 0,
          code: "abc",
        },
        {
          uses: null,
          from: { _seconds: 1634309750, _nanoseconds: 651000000 },
          to: { _seconds: 1634914500, _nanoseconds: 0 },
          code: "abcd",
        },
        {
          from: { _seconds: 1638267028, _nanoseconds: 580000000 },
          uses: 1,
          couponNote: "",
          to: { _seconds: 1638267028, _nanoseconds: 580000000 },
          code: "Test",
        },
        {
          code: "Test12",
          from: { _seconds: 1638267028, _nanoseconds: 580000000 },
          couponNote: "",
          to: { _seconds: 1638267028, _nanoseconds: 0 },
          uses: 1,
        },
        {
          code: "gjorgji",
          couponNote: "",
          to: { _seconds: 1640939741, _nanoseconds: 0 },
          uses: 3000,
          from: { _seconds: 1638347741, _nanoseconds: 679000000 },
        },
      ],
    },
    fees: { onlineFee: 10, priorityFee: 100, deliveryFeePerKm: 20 },
    filters: {
      occupations: [
        {
          imageUrl:
            "https://firebasestorage.googleapis.com/v0/b/klikni-jadi-platform.appspot.com/o/global%2Fmedia%2F3953103-middle.png?alt=media&token=1247ea0e-0f24-41d0-88bc-19e9a0ab1d2e",
          active: true,
          id: "H5j7T0C7894o5URtd4We",
          name: { en: "Restaurant", mk: "Ресторан" },
        },
        {
          active: true,
          id: "pq4L2oapPpgWfPHCbBB9",
          name: { en: "Lounge Bar", mk: "Ланџ" },
        },
        {
          id: "dLCMfY9nkuoDsbte1vOG",
          name: { mk: "Коктел-Бар", en: "Cocktail-Bar" },
          active: true,
        },
        {
          name: { mk: "Сендвичара", en: "Burger" },
          id: "DvpIbS2JCvNSzWwk32BJ",
          active: true,
        },
        {
          active: true,
          id: "Snbvuc0hai5WMNWZSfUe",
          name: { mk: "Фајн дајн", en: "Fine dine" },
        },
        {
          name: { en: "Wine and Dine", mk: "Вино и вечера" },
          active: true,
          id: "OUBT20o1DpChBS2eFaPk",
        },
        {
          id: "VdtGa0bzEV49v2r7OUEi",
          name: { mk: "Паб", en: "Pub" },
          active: false,
        },
      ],
      amenities: [
        {
          name: { en: "Pet-Friendly", mk: "Милениче" },
          id: "SpCetVx5yYDFBKuH1Jzx",
          active: true,
        },
        {
          name: { mk: "Wi-Fi", en: "Wi-Fi" },
          active: true,
          id: "3oJaIePQbm9EZjGcPUMU",
        },
        {
          id: "5UUkXFIpS6keQ0Bxh0la",
          name: { en: "Parking", mk: "Паркинг" },
          active: true,
        },
      ],
      cuisines: [
        {
          id: "tWXWMwhMEjMNQftqyYlg",
          imageUrl:
            "https://firebasestorage.googleapis.com/v0/b/klikni-jadi-platform.appspot.com/o/global%2Fmedia%2Fmkfood.jpeg?alt=media&token=a86bfafc-ea3b-42a6-a2a3-873f13bfe061",
          active: true,
          name: { en: "Macedonian", mk: "Македонска" },
        },
        {
          name: { mk: "Мексиканска", en: "Mexican" },
          id: "tMKRDwh9XLsnSC8Viysl",
          active: true,
          imageUrl:
            "https://firebasestorage.googleapis.com/v0/b/klikni-jadi-platform.appspot.com/o/global%2Fmedia%2Fmexicanfood.png?alt=media&token=01c5d4ca-28fa-45ff-a43e-9a2c52700544",
        },
        {
          name: { en: "Chinese", mk: "Кинеска" },
          imageUrl:
            "https://firebasestorage.googleapis.com/v0/b/klikni-jadi-platform.appspot.com/o/global%2Fmedia%2Fchinesefood.png?alt=media&token=2ddc2f46-a5d5-4697-9a91-9070a3b68725",
          id: "dhVg4rMQ7lUi5UK32gZo",
          active: true,
        },
        {
          id: "PLOlo59hKidgwihb1GXJ",
          active: true,
          imageUrl:
            "https://firebasestorage.googleapis.com/v0/b/klikni-jadi-platform.appspot.com/o/global%2Fmedia%2Famericanfood.jpeg?alt=media&token=1446df95-16ae-4da3-a514-010eda19d0fa",
          name: { mk: "Американска", en: "American" },
        },
        {
          name: { en: "Vegeterian", mk: "" },
          active: true,
          id: "gWJaSNXD9ZtumpN7wJog",
          imageUrl:
            "https://firebasestorage.googleapis.com/v0/b/klikni-jadi-platform.appspot.com/o/global%2Fmedia%2Fvegefood.png?alt=media&token=face425b-d2f3-4707-abe3-0bf085f3d38c",
        },
        {
          imageUrl:
            "https://firebasestorage.googleapis.com/v0/b/klikni-jadi-platform.appspot.com/o/global%2Fmedia%2Fturkishfood.jpeg?alt=media&token=36af2235-2dc4-4359-a03f-eb06adf05976",
          id: "mSVWkcoZZHD7TGVNTKaY",
          active: true,
          name: { mk: "Турска", en: "Turkish" },
        },
        {
          name: { mk: "Веганска", en: "Vegan" },
          active: true,
          imageUrl:
            "https://firebasestorage.googleapis.com/v0/b/klikni-jadi-platform.appspot.com/o/global%2Fmedia%2Fveganfood.jpg?alt=media&token=ac1e1572-8c91-432d-850f-1b81715b510b",
          id: "psJhAYoCd45KDa1CxQH7",
        },
        {
          name: { mk: "Здрава", en: "Healthy" },
          active: true,
          id: "1CLi8NrxDRV749AO6a6p",
          imageUrl:
            "https://firebasestorage.googleapis.com/v0/b/klikni-jadi-platform.appspot.com/o/global%2Fmedia%2Fhealthyfood.jpeg?alt=media&token=5a262558-d41e-4109-b763-0e2ca8332684",
        },
        {
          active: true,
          name: { en: "Italian", mk: "Италијанска" },
          imageUrl:
            "https://firebasestorage.googleapis.com/v0/b/klikni-jadi-platform.appspot.com/o/global%2Fmedia%2Fitalianfood.png?alt=media&token=1cbed29d-169d-41a3-bacb-2c012e45fd09",
          id: "focLCUTN2a8ypUrszVRj",
        },
        {
          imageUrl:
            "https://firebasestorage.googleapis.com/v0/b/klikni-jadi-platform.appspot.com/o/global%2Fmedia%2Fgreefood.png?alt=media&token=9521da3a-91e5-474c-91a6-a4833729df7e",
          active: true,
          name: { en: "Greek", mk: "Грчка" },
          id: "f3TP3k4JcSJw6iM2NPzr",
        },
        {
          id: "pDWAAAhAejDMSsA1Ack2",
          name: { en: "Bosnian", mk: "Босанска" },
          active: true,
        },
        {
          id: "o6fm6GlsI9L1cgTBmMZK",
          name: { mk: "Азиска", en: "Asian" },
          active: true,
        },
      ],
    },
    global: { orderNo: 1816, reservationNo: 1030 },
    pricing: {
      id: "pricing",
      markup: { takeout: 50, inhouse: 50, internal: 50, delivery: 50 },
      rabat: { internal: 0, delivery: 0, inhouse: 0, takeout: 0 },
      round: { internal: 0, inhouse: 0, takeout: 0, delivery: 0 },
    },
  };
};

export const getFoodMenu = () => {
  return {
    foodMenu: {
      name: "FRUIT LAND menu",
      categories: {
        co6nuoAwYNoo13Sc5Fus: {
          id: "co6nuoAwYNoo13Sc5Fus",
          name: {
            mk: "Ладно Цедени Сокови 400мл.",
            en: "Ладно Цедени Сокови 400мл.",
          },
          sortNo: 1,
        },
        bF3F7OqmVPyYXHUv8mI9: {
          name: { en: "Оброци", mk: "Оброци" },
          sortNo: 1,
          id: "bF3F7OqmVPyYXHUv8mI9",
        },
        "1mTogW5R2AKTMd0F1DiW": {
          name: { en: "Овошни Салати 500гр.", mk: "Овошни Салати 500гр." },
          id: "1mTogW5R2AKTMd0F1DiW",
          sortNo: 1,
        },
        p5NHb2RcenHwgk3j2x2c: {
          id: "p5NHb2RcenHwgk3j2x2c",
          sortNo: 1,
          name: { en: "Промотивно Мени", mk: "Промотивно Мени" },
        },
        GtFdN741Q8oUokTCDTmk: {
          name: { mk: "Смути 400мл", en: "Смути 400мл" },
          id: "GtFdN741Q8oUokTCDTmk",
          sortNo: 1,
        },
      },
      createdAt: { _seconds: 1632222468, _nanoseconds: 778000000 },
      active: true,
    },
    foodItems: [
      {
        categoryId: "GtFdN741Q8oUokTCDTmk",
        vat: 5,
        itemNo: "54067",
        available: true,
        prepTime: null,
        imageRef: "",
        imageName: "",
        description: { mk: "банана, какао, бадемово млеко", en: "" },
        discountedPrice: 150,
        ingredients: ["cheese", "doublecheese"],
        basePrice: 130,
        id: "2CTBF1nA5r0ERl2v8wMa",
        name: { mk: "Чоколадно Смути", en: "Чоколадно Смути" },
        imageUrl: "",
        finalPrice: 150,
        portions: null,
      },
      {
        available: true,
        description: { mk: "спанаќ, лимон, зелено јаболко, банана", en: "" },
        imageName: "",
        id: "2Zl0Sgv9JRO4cqHlWkCV",
        imageUrl: "",
        finalPrice: 150,
        ingredients: null,
        prepTime: null,
        name: { mk: "Зелено Смути", en: "Зелено Смути" },
        basePrice: 130,
        itemNo: "54066",
        portions: null,
        imageRef: "",
        categoryId: "GtFdN741Q8oUokTCDTmk",
        vat: 5,
      },
      {
        finalPrice: 110,
        vat: 5,
        ingredients: null,
        portions: null,
        imageRef: "",
        categoryId: "co6nuoAwYNoo13Sc5Fus",
        imageName: "",
        imageUrl: "",
        name: { en: "Тропски Микс Цеден", mk: "Тропски Микс Цеден" },
        itemNo: "54058",
        description: { mk: "портокал, ананас, лимон, јагода", en: "" },
        id: "4rS1kxqhyt0TP0f4qwAR",
        basePrice: 100,
        available: true,
        prepTime: null,
      },
      {
        finalPrice: 150,
        vat: 5,
        prepTime: null,
        imageName: "",
        categoryId: "GtFdN741Q8oUokTCDTmk",
        imageRef: "",
        id: "70LDxdPCpx4tjDtGCDBu",
        itemNo: "54063",
        imageUrl: "",
        available: true,
        portions: null,
        ingredients: null,
        basePrice: 130,
        description: { mk: "круша, јагода, банана", en: "" },
        name: { en: "Анти Стрес", mk: "Анти Стрес" },
      },
      {
        finalPrice: 150,
        imageUrl: "",
        ingredients: null,
        imageName: "",
        prepTime: null,
        available: true,
        itemNo: "54065",
        basePrice: 130,
        imageRef: "",
        description: { en: "", mk: "шумско овошје, сок од цвекло, банана" },
        portions: null,
        categoryId: "GtFdN741Q8oUokTCDTmk",
        name: { en: "Смути Од Шумско Овошје", mk: "Смути Од Шумско Овошје" },
        vat: 5,
        id: "CQqYPDEV1mnNXe8acDGv",
      },
      {
        available: true,
        finalPrice: 140,
        vat: 5,
        portions: null,
        ingredients: null,
        description: {
          en: "",
          mk: "зелено јаболко, спанаќ, краставица, лимон",
        },
        imageName: "",
        categoryId: "co6nuoAwYNoo13Sc5Fus",
        id: "DD5lnFg4tAS3XFANLuFj",
        itemNo: "54062",
        basePrice: 120,
        imageRef: "",
        imageUrl: "",
        prepTime: null,
        name: { mk: "Зелен Цеден Сок", en: "Зелен Цеден Сок" },
      },
      {
        available: true,
        description: { en: "", mk: "цитрон, лимон, мед , мраз" },
        imageUrl: "",
        portions: null,
        name: { en: "Розов Цитрон Цеден", mk: "Розов Цитрон Цеден" },
        categoryId: "co6nuoAwYNoo13Sc5Fus",
        finalPrice: 110,
        vat: 5,
        imageName: "",
        id: "DQh6H5sCVeMCGBbyCdBH",
        ingredients: null,
        prepTime: null,
        basePrice: 100,
        itemNo: "54055",
        imageRef: "",
      },
      {
        available: true,
        description: { mk: "банана, путер од кикирики, млеко", en: "" },
        imageUrl: "",
        portions: null,
        vat: 5,
        imageName: "",
        finalPrice: 150,
        ingredients: null,
        itemNo: "54068",
        prepTime: null,
        categoryId: "GtFdN741Q8oUokTCDTmk",
        name: {
          en: "Смути Со Путер Од Кикирики",
          mk: "Смути Со Путер Од Кикирики",
        },
        basePrice: 130,
        imageRef: "",
        id: "DZoKY9R5MRW2hkAwM63i",
      },
      {
        imageRef: "",
        description: { en: "", mk: "целер, јаболко, лимон" },
        finalPrice: 140,
        portions: null,
        categoryId: "co6nuoAwYNoo13Sc5Fus",
        name: { mk: "Сок Од Целер Цеден", en: "Сок Од Целер Цеден" },
        itemNo: "54061",
        ingredients: null,
        prepTime: null,
        imageUrl: "",
        basePrice: 120,
        available: true,
        vat: 5,
        id: "Hz52mPPcyOqJs1XfF2Sp",
        imageName: "",
      },
      {
        basePrice: 140,
        imageName: "",
        categoryId: "GtFdN741Q8oUokTCDTmk",
        finalPrice: 160,
        prepTime: null,
        imageRef: "",
        portions: null,
        name: { mk: "Енергетско Смути", en: "Енергетско Смути" },
        itemNo: "54069",
        imageUrl: "",
        description: { mk: "сурутка, банана, млеко, јагода", en: "" },
        ingredients: null,
        id: "NtjKtbu4Le4oXAuYRvUz",
        vat: 5,
        available: true,
      },
      {
        basePrice: 100,
        prepTime: null,
        itemNo: "54051",
        id: "QpJiqOpJygmwhsRQPpkn",
        portions: null,
        description: { en: "", mk: "јаболко, портокал, морков" },
        ingredients: null,
        vat: 5,
        name: { en: "Основен Цеден", mk: "Основен Цеден" },
        available: true,
        imageName: "",
        categoryId: "co6nuoAwYNoo13Sc5Fus",
        finalPrice: 110,
        imageRef: "",
        imageUrl: "",
      },
      {
        portions: null,
        finalPrice: 110,
        vat: 5,
        imageRef: "",
        prepTime: null,
        id: "TFtJEL7x8fPzFfqCgP6S",
        name: { mk: "Киви Микс Цеден", en: "Киви Микс Цеден" },
        imageName: "",
        ingredients: null,
        imageUrl: "",
        description: { en: "", mk: "јаболко, киви, портокал" },
        basePrice: 100,
        available: true,
        itemNo: "54054",
        categoryId: "co6nuoAwYNoo13Sc5Fus",
      },
      {
        ingredients: null,
        vat: 5,
        description: { en: "", mk: "портокал, цвекло, лимон" },
        categoryId: "co6nuoAwYNoo13Sc5Fus",
        imageName: "",
        available: true,
        id: "U6wp774WVE117bAe5C7g",
        prepTime: null,
        basePrice: 100,
        name: {
          mk: "Портокалово Цвекло Цеден",
          en: "Портокалово Цвекло Цеден",
        },
        finalPrice: 110,
        imageRef: "",
        itemNo: "54053",
        imageUrl: "",
        portions: null,
      },
      {
        imageName: "",
        imageUrl: "",
        basePrice: 110,
        vat: 5,
        itemNo: "54070",
        portions: null,
        categoryId: "1mTogW5R2AKTMd0F1DiW",
        available: true,
        name: {
          mk: "Овошна Салата Од Сезонско Овошје",
          en: "Овошна Салата Од Сезонско Овошје",
        },
        imageRef: "",
        finalPrice: 130,
        description: { mk: "", en: "" },
        id: "WK980yMP8HsW5YmcA58l",
        ingredients: null,
        prepTime: null,
      },
      {
        ingredients: null,
        portions: null,
        imageName: "",
        basePrice: 130,
        imageRef: "",
        description: {
          en: "",
          mk: "чиа, бадемово млеко, банана, малина, ананас",
        },
        vat: 5,
        available: false,
        prepTime: null,
        imageUrl: "",
        id: "aR764hEG8I15bul43cqy",
        itemNo: "54072",
        categoryId: "bF3F7OqmVPyYXHUv8mI9",
        finalPrice: 150,
        name: {
          mk: "Чиа Пудинг Со Бадемово Млеко",
          en: "Чиа Пудинг Со Бадемово Млеко",
        },
      },
      {
        available: true,
        imageRef: "",
        basePrice: 100,
        vat: 5,
        categoryId: "co6nuoAwYNoo13Sc5Fus",
        portions: null,
        name: { mk: "Сок Од Морков Цеден", en: "Сок Од Морков Цеден" },
        description: { en: "", mk: "морков, лимон, ѓумбир" },
        itemNo: "54057",
        imageName: "",
        id: "bNiDJWpf4QSBgZjLFwhE",
        prepTime: null,
        finalPrice: 110,
        ingredients: null,
        imageUrl: "",
      },
      {
        name: { en: "Зелена Лимонада Цеден", mk: "Зелена Лимонада Цеден" },
        portions: null,
        prepTime: null,
        available: true,
        imageUrl: "",
        finalPrice: 110,
        itemNo: "54056",
        ingredients: null,
        imageName: "",
        basePrice: 100,
        categoryId: "co6nuoAwYNoo13Sc5Fus",
        imageRef: "",
        description: { en: "", mk: "зелено јаболко, лимон, нане, мраз" },
        vat: 5,
        id: "eY045UD2v7E3MRlT2VRo",
      },
      {
        imageUrl: "",
        categoryId: "co6nuoAwYNoo13Sc5Fus",
        id: "fYa09uea5i7j929kS0OF",
        ingredients: null,
        portions: null,
        finalPrice: 140,
        basePrice: 120,
        available: true,
        imageName: "",
        itemNo: "54059",
        vat: 5,
        imageRef: "",
        description: { mk: "бејби спанаќ, јаболко, морков, лимон", en: "" },
        name: { en: "Сок Од Спанаќ Цеден", mk: "Сок Од Спанаќ Цеден" },
        prepTime: null,
      },
      {
        itemNo: "54064",
        prepTime: null,
        imageUrl: "",
        available: true,
        ingredients: null,
        categoryId: "GtFdN741Q8oUokTCDTmk",
        vat: 5,
        imageRef: "",
        description: { mk: "ананас, јагода, портокал, банана", en: "" },
        basePrice: 130,
        portions: null,
        finalPrice: 150,
        imageName: "",
        id: "sifvmeFfdNWUpzQute9t",
        name: { mk: "Егзотично Смути", en: "Егзотично Смути" },
      },
      {
        imageRef: "",
        prepTime: null,
        imageUrl: "",
        name: { en: "Црвен Витамин Цеден", mk: "Црвен Витамин Цеден" },
        basePrice: 100,
        description: { mk: "цвекло, морков, јаболко, лимон", en: "" },
        id: "vhDy0FLA480cN9x6Tn8V",
        portions: null,
        available: true,
        itemNo: "54052",
        categoryId: "co6nuoAwYNoo13Sc5Fus",
        imageName: "",
        vat: 5,
        finalPrice: 110,
        ingredients: null,
      },
      {
        ingredients: null,
        finalPrice: 150,
        available: false,
        imageName: "",
        imageUrl: "",
        vat: 5,
        name: {
          mk: "Чиа Пудинг Со Кокосово Млеко",
          en: "Чиа Пудинг Со Кокосово Млеко",
        },
        imageRef: "",
        categoryId: "bF3F7OqmVPyYXHUv8mI9",
        id: "wOTVKRuzoNfAwSMtK93U",
        portions: null,
        itemNo: "54071",
        prepTime: null,
        description: {
          mk: "чиа, кокосово млеко, банана, малина, ананас",
          en: "",
        },
        basePrice: 130,
      },
    ],
  };
};
